using System;

public class MeleeObject
{
    public string[] objects = new string[]
	{
		"Broken Longsword",
		"Carrot",
		"Fists",
		"Fists with Brawler perk",
		"Kick",
		"Kick with T3 legs",
		"Lute",
		"Rusty Longsword",
		"Short Sword",
		"Training Sword", 
		"Wooden Mallet", 
		"Dagger",
		"Heavy Branch",
		"Quarterstaff",
		"Wooden Shovel",
		"Broken Arming Sword",
		"Carving Knife",
		"Cleaver",
		"Pitchfork",
		"Rake",
		"Rusty Arming Sword",
		"Blacksmith Hammer",
		"Warhammer",
		"Axe",
		"Sickle",
		"Arming Sword",
		"Frying Pan",
		"Falchion",
		"Heavy Handaxe", 
		"Short Spear", 
		"Mace",
		"Bastard Sword",
		"Hoe",
		"Rapier",
		"Rusty Fork",
		"Billhook",
		"Longsword",
		"Battle Axe",
		"Club",
		"Messer",
		"Pickaxe",
		"Rusty Shovel",
		"Scythe",
		"Sledgehammer",
		"War Axe",
		"Estoc",
		"Falx",
		"Pole Axe",
		"Eveningstar",
		"Executioner's Sword",
		"Greatsword",
		"Maul",
		"Bardiche",
		"Halberd",
		"Polehammer",
		"Zweihander",
		"Spear"
	};

	public string[] properties = new string[]
	{
		"windup ms",
		"release ms",
		"recovery ms",
		"combo time in ms",
		"length in cm",
		"wood damage",
		"stone damage",
		"projectile speed",
		"damage to t0 head",
		"damage to t0 torso",
		"damage to t0 legs",
		"damage to t1 head",
		"damage to t1 torso",
		"damage to t1 legs",
		"damage to t2 head",
		"damage to t2 torso",
		"damage to t2 legs",
		"damage to t3 head",
		"damage to t3 torso",
		"damage to t3 legs",
		"stamina negation",
		"stamina damage"
	};
}
